### ISSUE TITLE
Unable to run real_time_transcription.py

### ISSUE THREAD

**Issue by sleekmike** [ahmedbesbes/assemblyai#1]
Hi Ahmed,

I read your medium article and then decided to try to run your code but I keep getting the error below:

`ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)`

I am using an API key and I have tried a couple of solutions to fix the SSL issue but none have worked yet.
I will appreciate your help.

**Comment by AlphaSoftTech** [comment]
@ahmedbesbes
